# Generated by Django 5.0.3 on 2024-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0002_rename_name_plante_nom_remove_plante_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='nom_recherche',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
