# Generated by Django 5.0.3 on 2024-04-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0003_plante_nom_recherche'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='arrosage',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
