# Generated by Django 5.0.3 on 2024-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0004_plante_arrosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='cycle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='soleil',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
