# Generated by Django 5.0.3 on 2024-05-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0004_plante_arrosage_plante_cycle_plante_soleil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plante',
            name='nom_scientifique',
        ),
    ]
