# Generated by Django 5.0.3 on 2024-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0004_plante_arrosage_plante_cycle_plante_soleil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePlante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.CharField(max_length=200)),
            ],
        ),
    ]
