# Generated by Django 5.0.3 on 2024-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0005_remove_plante_nom_scientifique'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='nom_scientifique',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
