# Generated by Django 5.0.3 on 2024-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0008_alter_plante_nom_scientifique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='nom_scientifique',
            field=models.JSONField(),
        ),
    ]
