# Generated by Django 5.0.3 on 2024-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0009_alter_plante_nom_scientifique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='soleil',
            field=models.JSONField(),
        ),
    ]
