# Generated by Django 5.0.3 on 2024-05-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0005_imageplante'),
        ('gk_app', '0010_alter_plante_soleil'),
    ]

    operations = [
    ]
