# Generated by Django 5.0.3 on 2024-05-12 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0011_merge_0005_imageplante_0010_alter_plante_soleil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePlante',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='arrosage',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='nom_recherche',
        ),
        migrations.RemoveField(
            model_name='plante',
            name='soleil',
        ),
        migrations.AddField(
            model_name='plante',
            name='dans_jardin',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='ensoleillement',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='frequence_arrosage',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='image_API',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='image_personnel',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plante',
            name='nom_personnel',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom_scientifique',
            field=models.CharField(max_length=200),
        ),
    ]
