# Generated by Django 5.0.3 on 2024-05-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0012_delete_imageplante_remove_plante_arrosage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plante',
            old_name='image_personnel',
            new_name='image_personnelle',
        ),
    ]
