# Generated by Django 5.0.3 on 2024-05-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0013_rename_image_personnel_plante_image_personnelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='dans_jardin',
            field=models.BooleanField(max_length=200),
        ),
    ]
