# Generated by Django 5.0.3 on 2024-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0014_alter_plante_dans_jardin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='image_personnelle',
            field=models.URLField(),
        ),
    ]
