# Generated by Django 5.0.3 on 2024-05-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0017_alter_plante_image_personnelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plante',
            old_name='image_personnelle',
            new_name='image_personelle',
        ),
    ]
