# Generated by Django 5.0.3 on 2024-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0018_rename_image_personnelle_plante_image_personelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='dans_jardin',
            field=models.BooleanField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom_personnel',
            field=models.CharField(default='Sans nom', max_length=200),
        ),
    ]
