# Generated by Django 5.0.3 on 2024-05-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gk_app', '0019_alter_plante_dans_jardin_alter_plante_nom_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='id_perenual',
            field=models.CharField(default='', max_length=100),
        ),
    ]
